name: Rafi Art Blog
author: rafi rasyadi, gardis
url: https://rafi-sudo.github.io/rafiart/
baseurl: /rafiart
resume_site: 
description: tutorial rafi rasyadi, fyi, hunting jadul, jumat berkah, senin semangat, rafi rasyadi
github_username: rafi-sudo
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
